In [5]:
import numpy as np
distribution=np.random.normal(loc=1000*0.1, scale=np.sqrt(1000*0.1*(1-0.1)),size=2000000)
print((np.percentile(distribution,[2.5, 97.5])-1000*0.1)/1000*100)

[-1.86065661  1.85904171]


In [6]:
sample_sizes=np.array([1000, 750, 500, 250, 100])
ps=np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

errs = np.empty([len(ps), len(sample_sizes)])
for i in range(len(ps)):
    mean = sample_sizes * ps[i]
    std = np.sqrt(sample_sizes * ps[i] * (1 - ps[i]))
    sample_std = std / np.sqrt(sample_sizes)
    errs[i] = 1.96 * (sample_std / np.sqrt(sample_sizes))

print(np.around(errs,2))

[[0.02 0.02 0.03 0.04 0.06]
 [0.02 0.03 0.04 0.05 0.08]
 [0.03 0.03 0.04 0.06 0.09]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.04 0.04 0.06 0.1 ]
 [0.03 0.03 0.04 0.06 0.09]
 [0.02 0.03 0.04 0.05 0.08]
 [0.02 0.02 0.03 0.04 0.06]]


In [ ]:
#The rightmost column is incorrect